main:
  organization: HelloSkyy                                   # Organization name
  inventory_script: scripts/inventory_hosts.py              # Dynamic Inventory script location 
  default_timeout: 5                                        # Default timeout (what are we using this for?)
  ansible_private_key: ~/.ssh/ansible                       # Ansible private key file

server_ssh_bootstrap:
  enabled: true
  default_user: root

proxmox:
  proxmox: true                                             # Using Proxmox?       
  proxmox_paid_subscription: false                          # do you have a paid subscription?
  proxmox_cluster: true                                     # are you using a Proxmox cluster?
  proxmox_cluster_name: "ClusterFuck"                       # Name of your Proxmox cluster

ceph:
  enabled: true                                             # Using Ceph?
  proxmox_managed: false                                    # does proxmox manage Ceph or is it standalone? 
  version: reef                                             # quincy or reef?

tailscale:
  enabled: true                                             # Using Tailscale?          
  