---
- name: Comment out Proxmox enterprise repo (UI-style)
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb https://enterprise.proxmox.com'
    line: '# deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise'
    state: present
    create: yes

- name: Add Proxmox no-subscription repo
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    state: present
    filename: pve-no-subscription

- name: Comment out Ceph enterprise repo (always)
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: '^deb https://enterprise.proxmox.com/debian/ceph-{{ ceph.version }}'
    line: '# deb https://enterprise.proxmox.com/debian/ceph-{{ ceph.version }} {{ ansible_distribution_release }} enterprise'
    state: present
    create: yes
  when: ceph.ceph | default(false)

- name: Add Ceph no-subscription repo (only if Proxmox manages Ceph)
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/ceph-{{ ceph.version }} {{ ansible_distribution_release }} main"
    state: present
    filename: ceph-no-subscription
  when:
    - ceph.ceph | default(false)
    - ceph.proxmox_ceph | default(false)

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

